import localFont from "next/font/local";
import "./globals.css";
import { ThemeProvider } from '../components/ThemeContext.jsx'; // Adjust the import path if necessary


const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};




const Layout = ({ children }) => {
  return (
    <html lang="en">
      
      <body>
        <ThemeProvider>
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
};

export default Layout;


